import { AUTH_PERMISSIONS, AUTH_ROLES } from "../../auth/constants/authorization";

export const COMISION_ALLOWED_ROLES = [AUTH_ROLES.JUEZ, AUTH_ROLES.ARCHIVERO, AUTH_ROLES.INGENIERO];
export const COMISION_ADMIN_ROLES = [AUTH_ROLES.JUEZ, AUTH_ROLES.ARCHIVERO, AUTH_ROLES.INGENIERO];
export const COMISION_VOTE_PERMISSIONS = [AUTH_PERMISSIONS.VOTAR_LIBERTAD_CONDICIONAL];
export const COMISION_HISTORY_PERMISSION = AUTH_PERMISSIONS.GESTIONAR_VOTACIONES;
export const TOTAL_JUECES_COMISION = 5;
export const MAYORIA_NECESARIA_COMISION = 3;
export const COMISION_REPORT_CHUNK_SIZE = 5;
